//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int entityID { get; set; }
        public int addressTypeID { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string addressLine3 { get; set; }
        public string suburb { get; set; }
        public string city { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual Parish Parish { get; set; }
        public virtual Person Person { get; set; }
    }
}
