//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAddress
    {
        public int entityID { get; set; }
        public int emailAddressTypeID { get; set; }
        public string emailAddress1 { get; set; }
        public bool isDefault { get; set; }
    
        public virtual EmailAddressType EmailAddressType { get; set; }
        public virtual Parish Parish { get; set; }
        public virtual Person Person { get; set; }
    }
}
