//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ID { get; set; }
        public int parishUserID { get; set; }
        public decimal amount { get; set; }
        public int expenseTypeID { get; set; }
        public System.DateTime expenseDate { get; set; }
        public System.DateTime dateSubmitted { get; set; }
    
        public virtual ExpenseType ExpenseType { get; set; }
        public virtual ParishUser ParishUser { get; set; }
    }
}
